### ISSUE TITLE
Shards Rocks is no longer available.

### ISSUE THREAD

**Issue by faustinoaq** [shardsrocks/sharock#7]
Hi @pine I like this project but seems this is not longer available.

> I cannot maintenance can not be continued. Thank you.

Well, I think we can help with that :wink: 

We use https://shards.rocks to check [amberframework](https://github.com/amberframework/amber#welcome-to-amber) dependencies, maybe we can host it inside our sponsored DigitalOcean VPS, WDYT?

**Comment by faustinoaq** [comment]
We have a sponsored droplet with 2CPU 4GB RAM and 40GB SSD avaliable

And we're just using a tiny part of this :sweat_smile: 

![screenshot_20180609_090905](https://user-images.githubusercontent.com/3067335/41192529-c3f7da22-6bc4-11e8-9439-95bd0115092b.png)

Don't worry about the 800MB RAM usage, the Crystal Garbage Collector is not very frequent :sweat_smile: 

IMO This droplet can host many crystal apps at once :sunglasses:

**Comment by faustinoaq** [comment]
@drujensen @elorest @eliasjpr @pine WDYT?

**Comment by faustinoaq** [comment]
Maybe this repo can be moved to [crystal-community](https://github.com/crystal-community/) as well, @veelenga, WDYT?

**Comment by veelenga** [comment]
@faustinoaq yeah, that's a good addition.

**Comment by waghanza** [comment]
@pine I will be interested too in maintaining https://shards.rocks service (I can in my spare time)

@pine @faustinoaq @veelenga is this OK to move on `crystal-community ` ?

**Comment by veelenga** [comment]
I think it can stay here.

Probably @faustinoaq can add you to the list of collaborators.

**Comment by waghanza** [comment]
It will be a pleasure to collaborate :heart:

**Comment by faustinoaq** [comment]
@waghanza I've been busy with college and my new job. I just added you to  this repo :+1:

**Comment by waghanza** [comment]
Awesome, i've started to refactor. 

However, I've a question. What about hosting ? Has `crystal` **community** a sponsor ? I mean any provider that could host this service ? I even don't know if actual hosting is available.

**Comment by faustinoaq** [comment]
@waghanza We have discused it some time ago. Amber website hosting was sponsored by Digital Ocean. (I think still is being sponsored ping :bell: @elorest @eliasjpr) So I thought could be possible to create a minimal instance to host the new shards rocks (maybe refactored using amber :sweat_smile: ) WDYT?

**Comment by waghanza** [comment]
Hi @faustinoaq,

I think the first step to be made is to upgrade codebase to latest crystal :stuck_out_tongue: A complete refactoring will be too time consuming, and honestly, I'm not sure amber is the more relevant for this kind of app. 

* In the list of framework I know (`amber`, `lucky`, `kemal`, `spider-gazelle`, `orion`, `raze`, `router.cr`), I think https://github.com/atomframework/web will be my favorite (@vladfaust is working on it).
* For hosting, I think it will be helpful (for `crystal` **community**) to run of `aws`. The main argument behind that is to say 

> hey ! I'm running on `aws` with `crystal`, why not you ?

This main idea is to use `aws` usage to help `crystal` growing (I'm mean in jobs perspective ...). 
Also, technically a service like shards.rocks could massively use lambda to help tracking crystal deps (to reduce how time consumption in maintenance)

What do you think of it ?

**Comment by faustinoaq** [comment]
@waghanza Yeah,I like your idea :+1: 

> I think the first step to be made is to upgrade codebase to latest crystal stuck_out_tongue A complete refactoring will be too time consuming, and honestly, I'm not sure amber is the more relevant for this kind of app.

I agree 

BTW, I didn't know about atomframework, seems interesting :smile:

**Comment by waghanza** [comment]
@vladfaust is one of the contributor on https://github.com/the-benchmarker/web-frameworks and he have implemented https://github.com/vladfaust/crystalworld to test all `crystal` **features** and show the to the word :tada:

**Comment by vladfaust** [comment]
Thanks for the kind words guys, it's really heartwarming 😌 I'm doing my best working on the framework!

Regarding to shardsrocks (which needs renaming IMO), if the community needs, I can host it on my side. I'm sponsoring myself (and also some of my friends do sponsor me), so I always have server space. 

However, I ofthen think of some kind of centralized shards repository like npm or yarn with a CLI:

1. It's going to protect from unexpected code wipes (i.e. I can delete all my github repos).
2. It would allow to better work with licenses in an automative way.
3. It would do things faster than default shards (@ysbaddaden mentioned that refining it to do parallel checkouts would lead to a complex rewrite) and prettier than it.
4. It would handle dependencies.
5. It would display the number of downloads and have overall popularity chart - it's important to developers.
6. It would have an enterpsire option for private hosting, which would allow it to live long and prosper

I can't say that I'm going to implement it though, because I have other business ideas which have bigger profit/time coefficient. It's just my thoughts, I consider them useful to the community o/

**Comment by waghanza** [comment]
Hi @vladfaust,

Thanks for ideas :heart: however hosting solution could be found :stuck_out_tongue: but this question has to be (for me) thought for the whole `crystal` **community** (like  `crystal-ann` ..)

> 1. It's going to protect from unexpected code wipes (i.e. I can delete all my github repos)

Sure, but why ? Not sure this has any relation with **centralization** / **decentralization**, but what I know is that this **COULD** be `merge` with something like https://crystalshards.xyz  ala https://rubygems.org making a **central** point (in term of caching / backing up)

> 2. It would allow to better work with licenses in an automative way.

I don't understand this point

> 3. It would do things faster than default shards (@ysbaddaden mentioned that refining it to do parallel checkouts would lead to a complex rewrite) and prettier than it.

I do not understand the comparison point with `shards`

> 4. It would handle dependencies

Yes, I think a service like that have to, but it's rather an idea of submitting / validating `shard.yml`

> 5. It would display the number of downloads and have overall popularity chart - it's important to developers.

Yes, like https://packagist.org does

> 6. It would have an enterpsire option for private hosting, which would allow it to live long and prosper

Thinks kind of stuff is easy with **decentralization** (I mean `scm` with only private access)

PS : For example https://crates.io/ in `rust` is **decentralized**, but acts as a **registry** (think I think you might do in `crystal`)

**Comment by vladfaust** [comment]
Hey, @waghanza, I'll try to explain my points. 

1. First of all, merging with an existing solution means responsibility for its original maintainer. Regarding to https://crystalshards.xyz, we should ask @f first if he's ready to move out of the scope of a free heroku dyno and maintain much more features to make it similar to rubygems - caching, backing up, categories? 

> 2. I don't understand this point

Licensing is a tough thing, you should know that by now 😄 Resolving licensing conflicts is a nice thing to do automatically (e.g. warn about *GPL).

> 3. I do not understand the comparison point with shards

See https://github.com/crystal-lang/shards/issues/239.

> 6. Thinks kind of stuff is easy with decentralization (I mean scm with only private access)

It's not easy for businesses, which want to delegate work. And maintaining a private access VCS could be a trouble. I mean, npm and yarn do provide such kind of service, it means businesses need it.

**Comment by waghanza** [comment]
1. Agreed :+1: 
2. OK, but I think it of of scope. Warnings could be done, but is the author responsibility (I mean it not a **registry** thing)
3. Still don't get the point. A `registry` has **NOT** to override `package manager` work
4. Yeah, but this can be delegated with service like http://gemfury.com but it is, I my opinion, non open source maintainable (I mean this could not be done if devs are working on they spare time). For example **Packagist Conductors UG** is behind private http://packagist.com

**Comment by vladfaust** [comment]
Looks like I meant not a registry itself, but a package manager + registry. Just like yarn or npm, see? 😃 

There are two ways speaking of any infrastructure (not about registry particularly):

1. Decentralized way. A separate service for each task (e.g. registry, package manager, private registry in this case). That's cool and geeky and you could replace certain parts with your own solutions, but it has more potential failure points. And it would require more time to bundle all these services together. Also the question of maintaining - finances split between all these services lead to a poorer separate support.

2. Centralized way. Putting all eggs into one basket. However, if the service is global, it receives much more support (including financial), which drives the possibility of failure near to zero. And saves lots of time, because it's already done for you.

**Comment by waghanza** [comment]
I see your point @vladfaust. i was thinking of a mix : having a subcommand of `shards` (e.g : publish) and having ability to get dependencies define from `registry` (adding a key in `shard.yml` at the same level as `github`) that fetch metadata from the registry and retrieve source from vcs (so it let dev use directly github even with private/internal repo), but this is a long terme discussion, and we need to include @ysbaddaden

**Comment by faustinoaq** [comment]
Hi all crystal devs! 

I'm happy to announce that https://shards.rocks/ is alive again :tada: :100: 

I'm currently working on a refactoring using amber framework (no special reason, is just my favorite one)

I bought the domain and I'm using Amber Organization sponsorship by Digital Ocean to get a 5$ server to run this service.

I'm pretty impressed that I was able to run shards.rocks despite the fact that is running on  crystal 0.10.2 and kemal 0.7.0. This is the power of compiled programs :muscle: 

Thanks to @sdogruyol for kemal and crystal team (@bcardiff and others) for keeping crystal awesome :heart:

**Comment by faustinoaq** [comment]
Also this is a verified organization now

![image](https://user-images.githubusercontent.com/3067335/55671838-d1ff1680-5859-11e9-9aab-e001dc2fac2f.png)


PR, issues and bugfixes are welcome :+1:

**Comment by waghanza** [comment]
@faustinoaq is there any API I could use to add `crystal` support for @dependabot ?

**Comment by faustinoaq** [comment]
@waghanza Shardrocks uses an internal api to serve the vue font-end, you can see it [here](https://github.com/shardsrocks/sharock-server/blob/master/src/routes/api/package.cr), although, this api is still very basic :sweat_smile:
